#!/bin/bash

set -ex

#Make TOSZ
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
OUTPUT_DIR="$DIR/build"
echo "Checking if output directory exist"

if [ ! -d "$OUTPUT_DIR" ]; then
  echo "Creating output dir"
  mkdir "$DIR/build"
fi

echo "Make TOSZ"
pushd "$OUTPUT_DIR"
cmake "$DIR"
cmake --build .
popd
